### ISSUE TITLE
Can you help in computing shannon entropy of 5*5 matrix?

### ISSUE THREAD

**Issue by manvirvirk** [paolodalberto/SparseFastMM#4]

**Comment by paolodalberto** [comment]
let me check ...

**Comment by paolodalberto** [comment]
You may have multiple ways to do this and how to use it @manvirvirk 

1. if you do not care about the location in the matrix you just create an histogram, h_i, pi = hi / sum(h_i) and then I = -log p_i
2. you may split the matrix in four quadrant. 3x3, 3x3, 2x3, 2x2, you may compute the I for each sub-matrix, then you have 4 I
3. it is also function how you are going to use it

**Comment by paolodalberto** [comment]
does make sense ?

**Comment by paolodalberto** [comment]
@manvirvirk should I close this ?

**Comment by paolodalberto** [comment]
thank you
